services:
  archenovaapi:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ArcheNovaAPI
    ports:
      - "15667:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      # Weitere Umgebungsvariablen können hier hinzugefügt werden
    networks:
      - archenova-network
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: MongoDB
    environment:
      - 'MONGO_INITDB_DATABASE=archenova'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    networks:
      - archenova-network

networks:
  archenova-network:
    driver: bridge